Repository Chudopal/PythonDeveloperCheatSheet, pull requests merged in 2022-06, with the labels that each got.

#27 [#H13]Clinic SQL homework
  Shops/pizzeria/homeworks/clinic_queries.sql
Labels: ready for rewiev

#30 [#H13] Added the 8th item of the request
  Shops/beauty_saloon/homeworks/clinic_queries.sql
Labels: done!

#34 [#H13] Added clinic in SQL
  Shops/building_materials_store/app/Homework/clinic_queries.sql
Labels: done!

#36 [#H14] Added clinic queries
  Shops/household_shop/homeworks/clinic_base.sql
Labels: done!

#35 [#H13] Added Clinic sql part
  Shops/travel_guide_store/README.md
  Shops/travel_guide_store/app/main.py
  Shops/travel_guide_store/clinic_queries.sql
Labels: done!

#42 [H15] OOP tasks
  Shops/household_shop/homeworks/animals_world.py
  Shops/household_shop/homeworks/autosimulation.py
  Shops/household_shop/homeworks/employee_mng_system.py
Labels: done!

#48 [#DR02] Fix file for SQL
  Shops/rubiks_cube_shop/app/main.py
Labels: done!

#46 [#D03] Added OOP
  Shops/stationary_store/app/shopOOP.py
Labels: done!

#43 [#H15] Added exercise 1, 2
  Shops/building_materials_store/app/Homework/datastructures_OOP.py
Labels: done!

#38 [#H15]OOP homework
  Shops/pizzeria/homeworks/animal_world.py
  Shops/pizzeria/homeworks/employee_management_system.py
  Shops/pizzeria/homeworks/matrix.py
  Shops/pizzeria/homeworks/vehicle_simulation.py
Labels: ready for review

#52 [#H15] Added OOP_homework
  Shops/sport_atribute_shop/app/main.py
  Shops/sport_atribute_shop/home_work/[#H15] Animals.py
  Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
Labels: done!

#55 [#H17] Flask homework
  Shops/pizzeria/homeworks/flask_hw/1_task.py
  Shops/pizzeria/homeworks/flask_hw/2_task.py
  Shops/pizzeria/homeworks/flask_hw/3_task.py
  Shops/pizzeria/homeworks/flask_hw/4_task.py
  Shops/pizzeria/homeworks/flask_hw/5_task.py
  Shops/pizzeria/homeworks/flask_hw/storage.json
  Shops/pizzeria/homeworks/flask_hw/templates/3_task/schedule.html
  Shops/pizzeria/homeworks/flask_hw/templates/4_task/author_datail.html
  Shops/pizzeria/homeworks/flask_hw/templates/4_task/authors.html
  Shops/pizzeria/homeworks/flask_hw/templates/4_task/book_detail.html
  Shops/pizzeria/homeworks/flask_hw/templates/5_task/employee_service.html
Labels: done!

#51 [#H15] OOP homework
  Shops/rubiks_cube_shop/README.md
  Shops/rubiks_cube_shop/homeWork/homeWork15.py
Labels: done!

#54 [#D04] Shop SQL HW
  Shops/pizzeria/app/main.py
  Shops/pizzeria/app/migrations.sql
Labels: done!

#66 [#D04] Add SQL
  Shops/rubiks_cube_shop/app/main.py
Labels: done!

#62 [#H17] Flask_hw
  Shops/household_shop/homeworks/flask/1_task.py
  Shops/household_shop/homeworks/flask/2_task.py
  Shops/household_shop/homeworks/flask/3_task.py
  Shops/household_shop/homeworks/flask/4_task.py
Labels: done!

#68 [#HR] Bringing order in hw files
  Shops/pizzeria/homeworks/cards_app/cards.py
  Shops/pizzeria/homeworks/oop_hw/animal_world.py
  Shops/pizzeria/homeworks/oop_hw/employee_management_system.py
  Shops/pizzeria/homeworks/oop_hw/matrix.py
  Shops/pizzeria/homeworks/oop_hw/vehicle_simulation.py
  Shops/pizzeria/homeworks/sql_hw/clinic_queries.sql
Labels: done!

#67 [#H18] hospital_app HW
  Shops/pizzeria/homeworks/hospital_app/config.py
  Shops/pizzeria/homeworks/hospital_app/hospital.py
  Shops/pizzeria/homeworks/hospital_app/models.py
  Shops/pizzeria/homeworks/hospital_app/query_builder.py
  Shops/pizzeria/homeworks/hospital_app/routes.py
  Shops/pizzeria/homeworks/hospital_app/run.py
  Shops/pizzeria/homeworks/hospital_app/storage_handler.py
  Shops/pizzeria/homeworks/hospital_app/structure.sql
Labels: done!

#70 [#H20] Django HW
  Shops/pizzeria/homeworks/django_hw/bank/bank/__init__.py
  Shops/pizzeria/homeworks/django_hw/bank/bank/asgi.py
  Shops/pizzeria/homeworks/django_hw/bank/bank/settings.py
  Shops/pizzeria/homeworks/django_hw/bank/bank/urls.py
  Shops/pizzeria/homeworks/django_hw/bank/bank/wsgi.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/__init__.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/admin.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/apps.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/migrations/0001_initial.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/migrations/0002_auto_20220627_1145.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/migrations/0003_auto_20220627_1223.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/migrations/__init__.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/models.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/tests.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/urls.py
  Shops/pizzeria/homeworks/django_hw/bank/cards/views.py
  Shops/pizzeria/homeworks/django_hw/bank/manage.py
  Shops/pizzeria/homeworks/django_hw/bank/templates/base.html
  Shops/pizzeria/homeworks/django_hw/bank/templates/cards/accounts.html
  Shops/pizzeria/homeworks/django_hw/bank/templates/cards/cards.html
Labels: done!

#65 [#D04] Shop in SQL
  Shops/building_materials_store/app/main.py
Labels: done!

#40 [#H14] Added Sql Clinic
  Shops/car_shop/HomeWork/HomeWorkClinic.sql
  Shops/car_shop/app/main.py
Labels: done!
